---
deployment:
  tasks:
    - export SOURCEPATH=/home/sites/29a/7/7ded354faa/identoo.co/
    - export DEPLOYPATH=/home/sites/29a/7/7ded354faa/identoo.co/
    - echo "Deploying files to live path..."
    - /bin/cp -R $SOURCEPATH* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - echo "Deployment completed successfully" > $DEPLOYPATH/deploy.log
